server {
    listen 31450;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html index.htm;

    location ~* \.(js|css|map|png|jpg|jpeg|gif|webp|avif|ico|svg|woff|woff2|ttf|eot)$ {
      rewrite ^/(?:.*?/)?chart/(.*)$ /$1 last;
      try_files $uri =404;
      expires 30d;
      access_log off;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
    }
}
