import { getThemeColor } from '../../../../src/demo/theme';

export function createSearchChartOptions(source: Element | null) {
  const crosslineColor = getThemeColor(source, '--chart-crossline-color');
  const textColor = getThemeColor(source, '--text-secondary-color');

  return {
    smooth: true,
    voronoi: true,
    animate: {
      duration: 1000,
    },
    xAxis: {
      type: 'mapping',
      data: [
        '2025/06/23 15:00:00',
        '2025/06/23 16:00:00',
        '2025/06/23 17:00:00',
        '2025/06/23 18:00:00',
        '2025/06/23 19:00:00',
        '2025/06/23 20:00:00',
        '2025/06/23 21:00:00',
        '2025/06/23 22:00:00',
        '2025/06/23 23:00:00',
        '2025/06/24 00:00:00',
        '2025/06/24 01:00:00',
        '2025/06/24 02:00:00',
        '2025/06/24 03:00:00',
        '2025/06/24 04:00:00',
        '2025/06/24 05:00:00',
        '2025/06/24 06:00:00',
        '2025/06/24 07:00:00',
        '2025/06/24 08:00:00',
        '2025/06/24 09:00:00',
        '2025/06/24 10:00:00',
        '2025/06/24 11:00:00',
        '2025/06/24 12:00:00',
        '2025/06/24 13:00:00',
        '2025/06/24 14:00:00',
        '2025/06/24 15:00:00',
      ],
      showSplitLine: true,
      fontColor: textColor,
      lineColor: textColor,
    },
    yAxis: {
      type: 'value',
      showAixsText: true,
      showSplitLine: false,
      data: {
        start: 0,
        end: 58.27,
      },
      interval: 1000,
      title: {
        text: '百分比(%)',
      },
      fontColor: textColor,
      lineColor: textColor,
    },
    labels: {
      type: 'rect',
      fontSize: 14,
    },
    datasets: [
      {
        label: 'dev-a',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'dev-a',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'dev-assets',
        data: [
          31.8,
          31.8,
          31.8,
          29.6,
          29.6,
          29.6,
          29.6,
          29.6,
          29.6,
          29.6,
          29.7,
          29.7,
          29.7,
          29.7,
          29.7,
          29.7,
          29.7,
          29.7,
          29.7,
          29.7,
          29.7,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'dev-assets',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          29.7,
          29.7,
          29.7,
        ],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'dev-b',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'dev-b',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'dev-ckdk-test',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'dev-ckdk-test',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'dev-cxtest',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-cxtest',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
      {
        label: 'dev-default',
        data: [
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          12.5,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f7656a',
        missing: 'straight',
      },
      {
        label: 'dev-default',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          12.5,
          12.5,
          12.5,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-hk123-test',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'dev-hk123-test',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'dev-iiii',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'dev-iiii',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'dev-liu',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'dev-liu',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'dev-llm-train-demo',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'dev-llm-train-demo',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'dev-ls',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-ls',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
      {
        label: 'dev-ls0822',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f7656a',
        missing: 'straight',
      },
      {
        label: 'dev-ls0822',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-lste',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'dev-lste',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'dev-lstest',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'dev-lstest',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'dev-pvc-test',
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'dev-pvc-test',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'dev-qa-test',
        data: [6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, 6.5, null, null, null, null],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'dev-qa-test',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          6.5,
          6.5,
          6.5,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'dev-qatest1',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-qatest1',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
      {
        label: 'dev-qatest2',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f7656a',
        missing: 'straight',
      },
      {
        label: 'dev-qatest2',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-syytest1104',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'dev-syytest1104',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'dev-t4st',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'dev-t4st',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'dev-tanshengru',
        data: [
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          15.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'dev-tanshengru',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.38,
          15.38,
          15.38,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'dev-test',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'dev-test',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'dev-test-create',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-test-create',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
      {
        label: 'dev-test0602',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f7656a',
        missing: 'straight',
      },
      {
        label: 'dev-test0602',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-test0912',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'dev-test0912',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'dev-test1',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'dev-test1',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'dev-test3',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'dev-test3',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'dev-testa',
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'dev-testa',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'dev-testb',
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-testb',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
      {
        label: 'dev-testc',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f7656a',
        missing: 'straight',
      },
      {
        label: 'dev-testc',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-testhk',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'dev-testhk',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'dev-testhk12',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'dev-testhk12',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'dev-testhk123aaa12',
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'dev-testhk123aaa12',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'dev-testhk123aaa121',
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'dev-testhk123aaa121',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'dev-testhk123aaa1213',
        data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, null, null, null, null],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-testhk123aaa1213',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          0,
          0,
          0,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
      {
        label: 'dev-testll',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f7656a',
        missing: 'straight',
      },
      {
        label: 'dev-testll',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-testls',
        data: [
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          8.11,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'dev-testls',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          8.11,
          8.11,
          8.11,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'dev-ttt',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'dev-ttt',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'dev-z',
        data: [
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          15.63,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'dev-z',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          15.63,
          15.63,
          15.63,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'dev-zy',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'dev-zy',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'dev-zyc-test',
        data: [
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          9.38,
          null,
          null,
          null,
          null,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'dev-zyc-test',
        data: [
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          9.38,
          9.38,
          9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
      {
        label: '公共空间',
        data: [
          58.27, 58.27, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77, 56.77,
          56.77, 56.77, 56.77, 56.77, 56.77,
        ],
        lineWidth: 1.5,
        lineColor: '#f7656a',
        missing: 'straight',
      },
      {
        label: '快速开始_演示demo',
        data: [
          10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94, 10.94,
          10.94, 10.94, 10.94, 10.94, 10.94,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'Fx测试空间',
        data: [
          37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5, 37.5,
          37.5, 37.5,
        ],
        lineWidth: 1.5,
        lineColor: '#029be6',
        missing: 'straight',
      },
      {
        label: 'qatest',
        data: [
          19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23, 19.23,
          19.23, 19.23, 19.23, 19.23, 19.23,
        ],
        lineWidth: 1.5,
        lineColor: '#0053cf',
        missing: 'straight',
      },
      {
        label: 'qatest-zy',
        data: [
          39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06, 39.06,
          39.06, 39.06, 39.06, 39.06, 39.06,
        ],
        lineWidth: 1.5,
        lineColor: '#28cbd1',
        missing: 'straight',
      },
      {
        label: 'tenant-a',
        data: [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        lineWidth: 1.5,
        lineColor: '#29b6f2',
        missing: 'straight',
      },
      {
        label: 'cwz空间',
        data: [
          9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38,
          9.38, 9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#b472e0',
        missing: 'straight',
      },
      {
        label: 'mdm-test1',
        data: [
          9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38,
          9.38, 9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#ffa561',
        missing: 'straight',
      },
      {
        label: 'tenant-b',
        data: [
          9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38,
          9.38, 9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#e36fb7',
        missing: 'straight',
      },
      {
        label: 'tenant-c',
        data: [
          9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38,
          9.38, 9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#6bdb48',
        missing: 'straight',
      },
      {
        label: 'tenant-d',
        data: [
          9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38, 9.38,
          9.38, 9.38,
        ],
        lineWidth: 1.5,
        lineColor: '#f2db27',
        missing: 'straight',
      },
      {
        label: 'qatest-zx',
        data: [
          20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31, 20.31,
          20.31, 20.31, 20.31, 20.31, 20.31,
        ],
        lineWidth: 1.5,
        lineColor: '#6d63c7',
        missing: 'straight',
      },
    ],
    cross: {
      lineColor: textColor,
      voronoiColor: crosslineColor,
    },
    tooltip: {
      show: false,
    },
  };
}

export default createSearchChartOptions;
